### ISSUE TITLE
Unexpected Input for ']' 

### ISSUE THREAD

**Issue by zarghol** [johnpatrickmorgan/wtfautolayout#15] opened 2019-01-16 09:52 UTC
I have an error with a pasted log :
```
UNEXPECTED INPUT:
Line 5, Column 98
    "<NSLayoutConstraint:0x600003cb7200 V:|-(20)-[Common.LocalizableLabel:0x7fc0160d2170'Aujourd'hui']   (active, names: '|':MesComptes.ScheduleWidgetView:0x7fc0160d1f60 )>",
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
EXPECTED:
']'
```

Source : 
```
(
    "<NSLayoutConstraint:0x600003c69cc0 UILayoutGuide:0x6000025678e0'UIViewSafeAreaLayoutGuide'.bottom == UIImageView:0x7fc0160d1450.bottom + 20   (active)>",
    "<NSLayoutConstraint:0x600003c68cd0 UIImageView:0x7fc0160d1450.top == UILayoutGuide:0x6000025678e0'UIViewSafeAreaLayoutGuide'.top + 35   (active)>",
    "<NSLayoutConstraint:0x600003c63d90 MesComptes.HourGauge:0x7fc0160d03e0.height == 55   (active)>",
    "<NSLayoutConstraint:0x600003cb7200 V:|-(20)-[Common.LocalizableLabel:0x7fc0160d2170'Aujourd'hui']   (active, names: '|':MesComptes.ScheduleWidgetView:0x7fc0160d1f60 )>",
    "<NSLayoutConstraint:0x600003cb5f40 V:[Common.LocalizableLabel:0x7fc0160d2170'Aujourd'hui']-(20)-[MesComptes.HourGauge:0x7fc0160d03e0]   (active)>",
    "<NSLayoutConstraint:0x600003cb56d0 V:[Common.SelfSizedTableView:0x7fc0169a5800]-(20)-|   (active, names: '|':MesComptes.ScheduleWidgetView:0x7fc0160d1f60 )>",
    "<NSLayoutConstraint:0x600003cb5680 V:[MesComptes.HourGauge:0x7fc0160d03e0]-(30)-[Common.SelfSizedTableView:0x7fc0169a5800]   (active)>",
    "<NSLayoutConstraint:0x600003cb5e00 V:|-(0)-[MesComptes.PhoneWidgetView:0x7fc0160d0d70]   (active, names: '|':MesComptes.MCAgenciesSearchDetailHoursWidgetsView:0x7fc0160f2380 )>",
    "<NSLayoutConstraint:0x600003cb4500 MesComptes.PhoneWidgetView:0x7fc0160d0d70.bottom == MesComptes.ScheduleWidgetView:0x7fc0160d1f60.top   (active)>",
    "<NSLayoutConstraint:0x600003cb6b20 MesComptes.ScheduleWidgetView:0x7fc0160d1f60.bottom == MesComptes.DaysWidgetView:0x7fc0160f5fe0.top   (active)>",
    "<NSLayoutConstraint:0x600003cb5360 MesComptes.DaysWidgetView:0x7fc0160f5fe0.bottom == MesComptes.MCAgenciesSearchDetailHoursWidgetsView:0x7fc0160f2380.bottom   (active)>",
    "<NSLayoutConstraint:0x600003cb7070 'UIView-Encapsulated-Layout-Height' MesComptes.MCAgenciesSearchDetailHoursWidgetsView:0x7fc0160f2380.height == 0   (active)>",
    "<NSLayoutConstraint:0x600003c694f0 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x6000025678e0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':MesComptes.PhoneWidgetView:0x7fc0160d0d70 )>",
    "<NSLayoutConstraint:0x600003c6a580 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x6000025678e0'UIViewSafeAreaLayoutGuide']   (active, names: '|':MesComptes.PhoneWidgetView:0x7fc0160d0d70 )>"
)
```

**Comment by johnpatrickmorgan** [comment] 2019-01-16 13:59
Thanks for raising this issue. This is the same underlying problem as #8: The `'` character is used to delimit the identifier, and the parser does not currently handle identifiers which contain a `'` character.  Replacing both instances of `Aujourd'hui` with `Aujourd’hui` in the input overcomes the error (and incidentally `’` is apparently the [preferred character to use for apostrophes](https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html)). 

It would be good to support identifiers that contain the `'` character in the future. I'll close this issue as a duplicate of #8 and track any progress there, thanks again.

**Closed as completed** 2019-01-17 10:30 UTC
Labels: duplicate
